To make it compile and run in sukap and WCTE container
Acraplet/wc_calibration pull request #2
Opened 2023-03-20 05:36 UTC by kmtsui

Some setup procedures are changed to make it compile in sukap and WCTE container environment.
Also remove hardcoded file paths.

However the WCTE container does not contain python numpy/matplotlib libraries, and its ROOT does not have MINUIT2 minimizer. Better to ask Lauren to install those features in future release.

2023-03-23 13:43 UTC, Acraplet requested changes

2023-03-23 13:43 UTC, Acraplet commented on mPMTmapping/src/Makefile
I get lots of error when compiling ScatteringFitterBinned with c++11, is this necessary only because of the WCTE container limitations?

2023-03-24 02:03 UTC, kmtsui commented on mPMTmapping/src/Makefile
Funny I didn't see any error in compiling the same file. What does the errors look like?

2023-03-24 02:23 UTC, kmtsui commented on mPMTmapping/src/Makefile
However I do see many warnings. Will try to clean them up later.

2023-03-27 09:54 UTC, Acraplet commented on mPMTmapping/src/Makefile
Hi Ka Ming, sorry for the delay in replying. I think it is an issue of my root install, the error message starts with

`/home/ac4317/Laptops/Year1/WCTE/Root_codes/fit_data/root/include/ROOT/RConfig.hxx:48:4: error: #error "ROOT requires support for C++14 or higher."
   48 | #  error "ROOT requires support for C++14 or higher."
      |    ^~~~~
/home/ac4317/Laptops/Year1/WCTE/Root_codes/fit_data/root/include/ROOT/RConfig.hxx:50:5: error: #error "Pass `-std=c++14` as compiler argument."
   50 | #   error "Pass `-std=c++14` as compiler argument."
      |     ^~~~~
` 

And then I get errors such as 

`‘string_view’ in namespace ‘std’ does not name a type`

` error: ‘cbegin’ is not a member of ‘std’; did you mean ‘begin’?`

`error: ‘const_iterator’ does not name a type`

2023-03-31 08:37 UTC, kmtsui commented on mPMTmapping/src/Makefile
just pushed some fixes please try

2023-03-31 10:13 UTC, Acraplet reviewed
Hi Ka-Ming, thank you very much - the fix worked!

2023-03-31 10:13 UTC, merged